### ISSUE TITLE
nested comments for JSX not working

### ISSUE THREAD

**Issue by bernatfortet** [philsinatra/NestedCommentsVSCode#13]
Here's a video of what's happening to me:
https://streamable.com/9ezlo

Nested Comments version: 2.2.2 , also on 2.2.3
Vs Code version: Version 1.29.1
Mac OS Mojave

**Comment by philsinatra** [comment]
Is the file you're working on configured as a React Javascript file, or standard Javascript file? If the language is set to standard Javascript, the extension will not execute:

> File format not supported

Try specifically setting the language to _JavaScriptReact_

![screen shot 2018-11-19 at 8 09 00 am](https://user-images.githubusercontent.com/1465808/48709192-c4aafd80-ebd2-11e8-99e4-2f895fb144e9.png)

![screen shot 2018-11-19 at 8 09 15 am](https://user-images.githubusercontent.com/1465808/48709194-c7a5ee00-ebd2-11e8-962c-ff83887531f5.png)

**Comment by bernatfortet** [comment]
Gotcha, changing the language made it work.

.tsx files still don't work. It says: `File Format not supported!`

Also I have the following issue: https://streamable.com/vbko5

**Comment by philsinatra** [comment]
.tsx files will require an update to support Typescript, I can add support for this. For those files, you'll set your language mode to _typescriptreact_. I'll push an update through that adds support for `.ts` files.

For your other video, can you make a separate issue and explain exactly what's going on in your video? I can't really follow what you're trying to show me.

**Comment by philsinatra** [comment]
Your video with narration explains perfectly. 

Basing the functionality on user selection allows for a more predictable experience. There may be multiple comments within a section and the desired effect is to only effect specific areas within that area with this functionality, which is safely achieved by using the selection as the effected range.

Additionally, not everyone uses the same formatting settings for their code and in some cases there could be multiple elements on the same line. In those cases, it may not be ideal to have the entire line commented out since the user may only want to comment out certain elements nested in other elements that technically appear on the same line.
